metadata:
  name: nav-ovon-train
  namespace: argo
spec:

  templates:
    - name: main
      steps:
        - - name: prepare-output-dir
            template: prepare-output-dir
        - - name: nav-ovon-train-task
            template: nav-ovon-train-task
      # 新增：准备节点 —— 创建 train/{workflow.name} 目录
    - name: prepare-output-dir
      container:
        image: swr.cn-east-3.myhuaweicloud.com/meadow/busybox:1.36 
        command: ["/bin/sh", "-c"]
        args:
          - |
            set -eu
            mkdir -p "/mnt/train/{{workflow.name}}"
            echo "Created: /mnt/train/{{workflow.name}}"
        volumeMounts:
          - name: volume-data-platform
            mountPath: /mnt/train
            subPath: data-platform/model/objnav/ovon/experiments/train
    - name: nav-ovon-train-task
        # for debug start
      tolerations:
        - key: "workflows.argoproj.io/workflow-template"
          operator: "Equal"
          value: "nav-ovon-train"
          effect: "NoExecute"
      # for debug end 
      input:
        parameters:
          - nproc_per_node
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                - key: cce.cloud.com/cce-nodepool
                  operator: In
                  values: 
                    # - cce-z00562901-wf-v100-4
                    # - cce-z00562901-wf-v100
                    - cce-z00562901-wf-nodepool-debug
      container:
        name: ''
        image: swr.cn-east-3.myhuaweicloud.com/meadow/ovon:dev-cu113_v0.4
        command:
          - /bin/bash
          - '-c'
        args:
          - |
            # tail -f /dev/null
            set -Eeuo pipefail
            set -x
            chmod +x /workspace/ovon/pre_train.sh /workspace/ovon/post_train.sh
            /workspace/ovon/pre_train.sh \
            && export OMP_NUM_THREADS=1 \
            && export MKL_NUM_THREADS=1 \
            && export NPROC=$(nvidia-smi -L | wc -l) \ 
            && torchrun --standalone \
              --nproc_per_node=$NPROC \
              -m ovon.run \
              --run-type train \
              --exp-config {{workflow.parameters.exp-config}} \
              habitat_baselines.num_environments={{workflow.parameters.habitat_baselines__num_environments}} \
              habitat_baselines.total_num_steps={{workflow.parameters.habitat_baselines__total_num_steps}} \
            && /workspace/ovon/post_train.sh
        env:
          - name: WORKFLOW_NAME
            value: '{{workflow.name}}'
          - name: EXP_CONFIG
            value: '{{workflow.parameters.exp-config}}'
          - name: NVIDIA_VISIBLE_DEVICES
            value: "all"
          - name: NVIDIA_DRIVER_CAPABILITIES
            value: "compute,utility,graphics"
        resources:
          limits:
            nvidia.com/gpu: '1'
        volumeMounts:
          - name: volume-data-platform
            mountPath: >-
              /workspace/ovon/data/task_datasets/ovon
            subPath: data-platform/data/task_datasets/ovon
          - name: volume-data-platform
            mountPath: /workspace/ovon/data/scene_datasets/hm3d
            subPath: data-platform/data/scene_datasets/hm3d_v0.2
          - name: volume-data-platform
            mountPath: /workspace/ovon/output
            subPath: data-platform/model/objnav/ovon/experiments/train/{{workflow.name}}
          - name: dshm
            mountPath: /dev/shm
  entrypoint: main
  arguments:
    parameters:
      - name: habitat_baselines__num_environments
        value: 8
      - name: habitat__dataset__data_path
        value: 'data/task_datasets/ovon/hm3d/v1/{split}/{split}.json.gz'
      - name: habitat_baselines__total_num_steps
        value: 80000
      - name: exp-config
        value: config/experiments/202509/transformer_dagger_quick_debug.yaml
  volumes:
    - name: volume-data-platform
      persistentVolumeClaim:
        claimName: pvc-data-platform
    - name: dshm
      emptyDir:
        medium: Memory
        sizeLimit: 8Gi
  imagePullSecrets:
    - name: default-secret
